Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"
  config.vm.base_mac = nil

  config.vm.define "node1" do |node1| 
    node1.vm.hostname = "node1"
    node1.vm.network :forwarded_port, guest: 16443, host: 16443, id: "kubectl"
    node1.vm.network :private_network, ip: "192.168.56.101"
  end
  config.vm.define "node2" do |node2| 
    node2.vm.hostname = "node2"
    node2.vm.network :private_network, ip: "192.168.56.102"
  end

  # Public key setup
  config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/me.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL

  # Min Memory for k8s: 2048M
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "2048"]
  end

end
