apiVersion: v1
kind: Secret
metadata:
  name: "this-is-a-secret"
type: Opaque
data:
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  secret: {{ randAlphaNum 32 | b64enc | quote }}
